replicas: 1

config:
  DEBUG: "true"
  DB_PORT: "5432"
  DB_HOST: postgres.demo-system.svc.cluster.local
  DB_NAME: testdb
  DB_PARAMS: "sslmode=disable"

secret:
  create: false
  name: eventrouter-db

ingress:
  enabled: false

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
