replicas: 1

config:
  DEBUG: "true"

  DB_HOST: postgres.eventstack-system.svc.cluster.local
  DB_PORT: "5432"
  DB_USER: test
  DB_PASS: test
  DB_NAME: testdb
  DB_PARAMS: "sslmode=disable&connect_timeout=5&keepalives=1&keepalives_idle=30&keepalives_interval=10&keepalives_count=3"
  DB_READY_TIMEOUT: "4m"

service:
  port: 8084

secret:
  create: false
  name: eventrouter-db

ingress:
  enabled: false

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 128Mi
