{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_USER: {{ required "secret.DB_USER is required" .Values.secret.DB_USER | quote }}
  DB_PASS: {{ required "secret.DB_PASS is required" .Values.secret.DB_PASS | quote }}
{{- end }}
